name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # 중요: <REPO_NAME>을 실제 리포지토리 이름으로 변경하세요. (예: /memory-bread/)
        # 만약 username.github.io 리포지토리라면 "/" 만 입력하세요.
        run: flutter build web --base-href "/memory-bread/" --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web